using System;

namespace cna.poo {
    [Serializable]
    public enum Image_Enum {
        NA = 0,
        UTILITY_BORDER_001,
        UTILITY_MASK_001,
        LOGO_001,
        LOGO_002,

        //  AVATAR
        A_meeple_goldyx = 50,
        A_meeple_arythea,
        A_meeple_tovak,
        A_meeple_norowas,
        A_shield_green_goldyx,
        A_shield_red_arythea,
        A_shield_blue_tovak,
        A_shield_white_norowas,
        A_MEEPLE_RANDOM,


        //TERAIN
        TH_Black = 100,
        TH_Desert,
        TH_Forest,
        TH_Hill,
        TH_Lake,
        TH_Mountain,
        TH_Plains,
        TH_Swamp,
        TH_Wasteland,
        TH_Invalid,
        TH_Boarder,
        TH_YellowHex,
        TH_UnexploredAdvanced,
        TH_UnexploredBasic,
        TH_ExploreInner,
        TH_ExploreOuter,

        //STRUCTURE
        SH_CrystalMines_Blue = 200,
        SH_CrystalMines_Green,
        SH_CrystalMines_Red,
        SH_CrystalMines_White,
        SH_Draconum,
        SH_Keep,
        SH_MageTower,
        SH_MagicGlade,
        SH_MaraudingOrcs,
        SH_Monastery,
        SH_StartShrine,
        SH_Village,
        SH_AncientRuins,
        SH_Dungeon,
        SH_MonsterDen,
        SH_SpawningGround,
        SH_Tomb,
        SH_City_Blue,
        SH_City_Green,
        SH_City_Red,
        SH_City_White,

        //ICON
        I_angry = 300,
        I_armor,
        I_attack,
        I_boots,
        I_bow,
        I_cardBackRounded,
        I_catapult,
        I_crystal_black,
        I_crystal_blue,
        I_crystal_green,
        I_crystal_red,
        I_crystal_white,
        I_crystal_yellow,
        I_fame,
        I_healHand,
        I_influence,
        I_mana_black,
        I_mana_blue,
        I_mana_gold,
        I_mana_green,
        I_mana_red,
        I_mana_white,
        I_shield,
        I_smile,
        I_x,
        I_hourglass,
        I_moon,
        I_sun,
        I_search,
        I_basictile_small,
        I_coretile_small,
        I_influencegold,
        I_influencegrey,
        I_monsterarmor,
        I_resistfire,
        I_resistice,
        I_resistphysical,
        I_unitbanner,
        I_unitcity,
        I_unitkeep,
        I_unitmage,
        I_unitmonastery,
        I_unitvillage,
        I_monsterbrutal,
        I_attack_cold,
        I_attack_coldfire,
        I_attack_fire,
        I_monsterfortified,
        I_attack_normal,
        I_monsterparalyze,
        I_monsterpoison,
        I_monsterswift,
        I_monsterfame,
        I_disable,
        I_monsterselect,
        I_arrow_right,
        I_rip,
        I_blood,
        I_rest,
        I_dizzy,
        I_die_black,
        I_die_blue,
        I_die_gold,
        I_die_green,
        I_die_red,
        I_die_white,
        I_bootfly,
        I_cogwheel,
        I_trophy,
        I_info,
        I_check,
        I_warning,

        //CARD MISC
        C_deed_back = 400,
        C_wound,

        //CARD BASIC
        CB_battle_tranquility = 425,
        CB_battle_versatility,
        CB_cold_toughness,
        CB_concentration,
        CB_crystallize,
        CB_determination,
        CB_improvisation,
        CB_mana_draw,
        CB_march,
        CB_noble_manners,
        CB_promise,
        CB_rage,
        CB_stamina,
        CB_swiftness,
        CB_threaten,
        CB_tranquility,
        CB_will_focus,

        //CARD ADVANCED
        CA_agility = 500,
        CA_ambush,
        CA_blood_rage,
        CA_blood_ritual,
        CA_crushing_bolt,
        CA_crystal_mastery,
        CA_decompose,
        CA_diplomacy,
        CA_fire_bolt,
        CA_frost_bridge,
        CA_heroic_tale,
        CA_ice_bolt,
        CA_ice_shield,
        CA_intimidate,
        CA_into_the_heat,
        CA_in_need,
        CA_learning,
        CA_magic_talent,
        CA_mana_storm,
        CA_maximal_effect,
        CA_path_finding,
        CA_pure_magic,
        CA_refreshing_walk,
        CA_regeneration,
        CA_song_of_wind,
        CA_steady_tempo,
        CA_swift_bolt,
        CA_training,

        //CARD UNIT REGULAR
        CUR_foresters_x2 = 600,
        CUR_guardian_golems_x2,
        CUR_herbalists_x2,
        CUR_illusionists_x2,
        CUR_northern_monks,
        CUR_peasants_x3,
        CUR_red_cape_monks,
        CUR_savage_monks,
        CUR_utem_crossbowmen_x2,
        CUR_utem_guardsmen_x2,
        CUR_utem_swordsmen_x2,

        //  CARD UNIT ELITE
        CUE_altem_guardians_x3 = 650,
        CUE_altem_mages_x2,
        CUE_amotep_freezers_x2,
        CUE_amotep_gunners_x2,
        CUE_catapults_x3,
        CUE_fire_golems_x2,
        CUE_fire_mages_x2,
        CUE_ice_golems_x2,
        CUE_ice_mages_x2,

        // CARD ARTIFACT
        CT_amulet_of_darkness = 700,
        CT_amulet_of_sun,
        CT_banner_of_courage,
        CT_banner_of_fear,
        CT_banner_of_glory,
        CT_banner_of_protection,
        CT_book_of_wisdom,
        CT_diamond_ring,
        CT_emerald_ring,
        CT_endless_bag_of_gold,
        CT_endless_gem_pouch,
        CT_golden_grail,
        CT_horn_of_wrath,
        CT_ruby_ring,
        CT_sapphire_ring,
        CT_sword_of_justice,

        // CARD MONSTER GREEN
        CMG_back = 1000,
        CMG_cursed_hags_x2,
        CMG_diggers_x2,
        CMG_ironclads_x2,
        CMG_orc_summoners_x2,
        CMG_prowlers_x2,
        CMG_wolf_riders_x2,

        // CARD MONSTER GREY
        CMY_back = 1050,
        CMY_crossbowmen_x3,
        CMY_golems_x2,
        CMY_guardsmen_x3,
        CMY_swordsmen_x2,

        // CARD MONSTER BROWN
        CMB_back = 1100,
        CMB_crypt_worm_x2,
        CMB_gargoyle_x2,
        CMB_medusa_x2,
        CMB_minotaur_x2,
        CMB_werewolf_x2,

        // CARD MONSTER VIOLET
        CMV_back = 1150,
        CMV_fire_golems_x1,
        CMV_fire_mages_x2,
        CMV_ice_golems_x1,
        CMV_ice_mages_x2,
        CMV_illusionists_x2,
        CMV_monks_x2,

        // CARD MONSTER WHITE
        CMW_back = 1200,
        //CMW_altem_guardians_x2,
        CMW_altem_guardsmen_x2,
        CMW_altem_mages_x2,
        CMW_freezers_x3,
        CMW_gunners_x3,

        // CARD MONSTER RED
        CMR_back = 1250,
        CMR_fire_dragon_x2,
        CMR_high_dragon_x2,
        CMR_ice_dragon_x2,
        CMR_swamp_dragon_x2,

        // SKILLS GREEN GOLDYX
        SKG_back = 1400,
        SKG_flight,
        SKG_freezing_power,
        SKG_glittering_fortune,
        SKG_green_crystal_craft,
        SKG_motivation,
        SKG_red_crystal_craft,
        SKG_source_freeze,
        SKG_universal_power,
        SKG_white_crystal_craft,
        SKG_potion_making,
        // SKILLS RED ARYTHEA
        SKR_back = 1450,
        SKR_burning_power,
        SKR_dark_fire_magic,
        SKR_dark_negotiation,
        SKR_dark_paths,
        SKR_healing_ritual,
        SKR_hot_swordsmanship,
        SKR_invocation,
        SKR_motivation,
        SKR_polarization,
        SKR_power_of_pain,
        // SKILLS WHITE NOROWAS
        SKW_back = 1500,
        SKW_bonds_of_loyalty,
        SKW_bright_negotiation,
        SKW_day_sharpshooting,
        SKW_forward_march,
        SKW_inspiration,
        SKW_leadership,
        SKW_leaves_in_the_wind,
        SKW_motivation,
        SKW_prayer_of_weather,
        SKW_whisper_in_the_treetops,
        // SKILLS BLUE TOVAK
        SKB_back = 1550,
        SKB_cold_swordsmanship,
        SKB_double_time,
        SKB_i_dont_give_a_damn,
        SKB_i_feel_no_pain,
        SKB_mana_exploit,
        SKB_motivation,
        SKB_night_shooting,
        SKB_resistance_break,
        SKB_shield_mastery,
        SKB_who_needs_magic,

        // CARD SPELLS
        CS_fireball = 1600,
        CS_snowstorm,
        CS_expose,
        CS_tremor,
        CS_flame_wall,
        CS_mana_bolt,
        CS_whirlwind,
        CS_underground_travel,
        CS_burning_shield,
        CS_chill,
        CS_wings_of_wind,
        CS_restoration,
        CS_demolish,
        CS_space_bending,
        CS_call_to_arms,
        CS_meditation,
        CS_mana_meltdown,
        CS_mana_claim,
        CS_mind_read,
        CS_energy_flow,

        //  RUINS
        R_altars01 = 1650,
        R_altars02,
        R_altars03,
        R_altars04,
        R_back,
        R_enemies01,
        R_enemies02,
        R_enemies03,
        R_enemies04,
        R_enemies05,
        R_enemies06,
        R_enemies07,
        R_enemies08,

        //  TACTICS
        T_day_1 = 1700,
        T_day_2,
        T_day_3,
        T_day_4,
        T_day_5,
        T_day_6,
        T_night_1,
        T_night_2,
        T_night_3,
        T_night_4,
        T_night_5,
        T_night_6,
    }
}