namespace cna.poo {
    public enum MapHexId_Enum {
        None = 0,
        Invalid = 1,
        Basic_Back = 2,
        Core_Back = 3,
        Explore = 4,
        Start_A = 10,
        Start_B = 11,
        Basic_01 = 101,
        Basic_02,
        Basic_03,
        Basic_04,
        Basic_05,
        Basic_06,
        Basic_07,
        Basic_08,
        Basic_09,
        Basic_10,
        Basic_11,
        Core_01 = 201,
        Core_02,
        Core_03,
        Core_04,
        City_Green = 301,
        City_Blue,
        City_White,
        City_Red
    }
}
